// <auto-generated />
using System;
using CarRentalSystemSeparation.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalSystemSeparation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalSystemSeparation.Areas.Admin.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarRentalSystemSeparation.Areas.Vehicle.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 811, DateTimeKind.Utc).AddTicks(7447),
                            DisplayOrder = 1,
                            ImageUrl = "https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1200",
                            IsActive = true,
                            Subtitle = "Discover our fleet of luxury vehicles",
                            Title = "Premium Car Rental Experience"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 812, DateTimeKind.Utc).AddTicks(104),
                            DisplayOrder = 2,
                            ImageUrl = "https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1200",
                            IsActive = true,
                            Subtitle = "Book now and save up to 30%",
                            Title = "Best Deals on Car Rentals"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 812, DateTimeKind.Utc).AddTicks(109),
                            DisplayOrder = 3,
                            ImageUrl = "https://images.pexels.com/photos/627678/pexels-photo-627678.jpeg?auto=compress&cs=tinysrgb&w=1200",
                            IsActive = true,
                            Subtitle = "We're here to help you anytime",
                            Title = "24/7 Customer Support"
                        });
                });

            modelBuilder.Entity("CarRentalSystemSeparation.Areas.Vehicle.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 812, DateTimeKind.Utc).AddTicks(9961),
                            Description = "Comfortable and reliable sedan perfect for business trips and daily commuting.",
                            Features = "GPS Navigation, Bluetooth, Air Conditioning, Automatic Transmission",
                            ImageUrl = "https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400",
                            Make = "Toyota",
                            Model = "Camry",
                            PricePerDay = 65.00m,
                            Status = 0,
                            Type = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 813, DateTimeKind.Utc).AddTicks(4113),
                            Description = "Spacious SUV ideal for family trips and outdoor adventures.",
                            Features = "All-Wheel Drive, Backup Camera, Heated Seats, Cargo Space",
                            ImageUrl = "https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=400",
                            Make = "Honda",
                            Model = "CR-V",
                            PricePerDay = 85.00m,
                            Status = 0,
                            Type = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 813, DateTimeKind.Utc).AddTicks(4119),
                            Description = "Luxury sedan with premium features and exceptional performance.",
                            Features = "Premium Sound System, Leather Interior, Sport Mode, Premium Navigation",
                            ImageUrl = "https://images.pexels.com/photos/627678/pexels-photo-627678.jpeg?auto=compress&cs=tinysrgb&w=400",
                            Make = "BMW",
                            Model = "3 Series",
                            PricePerDay = 120.00m,
                            Status = 0,
                            Type = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 813, DateTimeKind.Utc).AddTicks(4122),
                            Description = "Iconic convertible sports car for an unforgettable driving experience.",
                            Features = "V8 Engine, Convertible Top, Sport Exhaust, Premium Audio",
                            ImageUrl = "https://images.pexels.com/photos/544542/pexels-photo-544542.jpeg?auto=compress&cs=tinysrgb&w=400",
                            Make = "Ford",
                            Model = "Mustang",
                            PricePerDay = 150.00m,
                            Status = 0,
                            Type = 3,
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 813, DateTimeKind.Utc).AddTicks(4125),
                            Description = "Large SUV perfect for group travel and cargo hauling.",
                            Features = "Third Row Seating, Towing Capacity, Entertainment System, Climate Control",
                            ImageUrl = "https://images.pexels.com/photos/1638459/pexels-photo-1638459.jpeg?auto=compress&cs=tinysrgb&w=400",
                            Make = "Chevrolet",
                            Model = "Tahoe",
                            PricePerDay = 95.00m,
                            Status = 0,
                            Type = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 28, 18, 35, 11, 813, DateTimeKind.Utc).AddTicks(4128),
                            Description = "Electric luxury sedan with cutting-edge technology and zero emissions.",
                            Features = "Autopilot, Supercharging, Premium Interior, Over-the-air Updates",
                            ImageUrl = "https://images.pexels.com/photos/919073/pexels-photo-919073.jpeg?auto=compress&cs=tinysrgb&w=400",
                            Make = "Tesla",
                            Model = "Model S",
                            PricePerDay = 180.00m,
                            Status = 0,
                            Type = 0,
                            Year = 2024
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
